version: '3.9'

services:
  mysql:
    image: mysql:8.0.29
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge
